# Generated by Django 5.2.3 on 2025-06-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_usuariopermitido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopermitido',
            name='codigo_validacion',
            field=models.CharField(max_length=20),
        ),
    ]
