# Generated by Django 5.2.3 on 2025-07-10 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_usuariopermitido_codigo_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
